### ISSUE TITLE
Video camera sensor does not render some objects

### ISSUE THREAD

**Issue by mdonahoe** [morse-simulator/morse#509]
When I create a video camera in the "outdoors" example, some of the boxes and fences are missing from the camera frame. Also, if I add a Victim robot, it will not appear in the camera frame either.

Everything displays correctly in the normal Blender window though.

My blind guess is that some objects end up on the wrong render layer somehow.

I am using MORSE 1.2 and Blender 2.62

**Comment by fdevillalobos** [comment]
Hey... how are you community??

So... not sure the SAME is happening to me here... but it sure looks worst than your case.
I've been at this for a couple of days and the only help I found online was to check if my Shading options were set to GLSL instead of multitexture.

In Blender my scene shows perfectly... and even when I use Blender Render... but not when I'm using morse or the Game Engine. The floor just WON'T RENDER... at all. Not only render... it won't appear. haha.

Here I have a screenshot of how it looks before launching morse, and after. Mind that I know the floor looks really fake... yes... but I'm not concentrating on looks for now... mainly functionality.

![not_rendered](https://cloud.githubusercontent.com/assets/6305634/7991198/3b181262-0aab-11e5-9e08-108ff50955a8.png)
![rendered](https://cloud.githubusercontent.com/assets/6305634/7991199/3b1bd942-0aab-11e5-9c6a-6d170995e0cd.png)

Any insights on what is going on?? Thanks a lot,
Francisco.

**Comment by adegroote** [comment]
On 04/Jun - 11:17, Francisco de Villalobos wrote:
> Hey... how are you community??
> 
> So... not sure the SAME is happening to me here... but it sure looks worst than your case.
> I've been at this for a couple of days and the only help I found online was to check if my Shading options were set to GLSL instead of multitexture.
> 
> In Blender my scene shows perfectly... and even when I use Blender Render... but not when I'm using morse or the Game Engine. The floor just WON'T RENDER... at all. Not only render... it won't appear. haha.
> 
> Here I have a screenshot of how it looks before launching morse, and after. Mind that I know the floor looks really fake... yes... but I'm not concentrating on looks for now... mainly functionality.
> 
> ![not_rendered](https://cloud.githubusercontent.com/assets/6305634/7991198/3b181262-0aab-11e5-9e08-108ff50955a8.png)
> ![rendered](https://cloud.githubusercontent.com/assets/6305634/7991199/3b1bd942-0aab-11e5-9c6a-6d170995e0cd.png)

I'm definitively not a Blender guru, so I won't help you so much on the
question. Through, if it does not render in viewport, it is not a Morse issue. You
can try to ask a question on blenderartists.org, the community there is
really helpful too.

**Comment by fdevillalobos** [comment]
That's the part that worries me and why I did not think it was a Blender problem... because when I use Blender render on the environment... it works!

![tower_c](https://cloud.githubusercontent.com/assets/6305634/8011090/900a7502-0b6a-11e5-8c7c-1ad6cffbbde8.png)

It just seems not to work when I use it loading the environment on Morse. But all the same I will ask on the blender forum. Thanks!!! And let me know if you have any other recommendations.

**Comment by severin-lemaignan** [comment]
Can you share a (minimal) blend file that exhibit the problem?
