### ISSUE TITLE
[Mac OS X] No Usable Version of Blender with Morse

### ISSUE THREAD

**Issue by tiberiusferreira** [morse-simulator/morse#574]
With Yosemite, Blender versions previous to 2.71 do not open. They return segmentation fault. But Morse requires a version lesser than 2.70, so it is not possible to use Morse at the moment with OS X.

**Comment by seantrott** [comment]
I've run into the same issue - according to the morse-simulator.rb file, I'm running 1.2.1 
(url 'https://github.com/morse-simulator/morse.git', :tag => '1.2.1'), but there is a Segmentation Fault when I run "morse check".

But if I try to use a Blender past 2.70 (as the first question indicates is desired), Morse rejects it, because it wants a Blender between 2.62 and 2.70.

In your first response, you mention changing "STRICT_MAX_BLENDER_VERSION". How can this be done?

**Comment by severin-lemaignan** [comment]
@seantrott as pointed before, MORSE 1.2.1 requires a 2.62 =< Blender version < 2.72 : cf https://github.com/morse-simulator/morse/blob/1.2.1/bin/morse.in#L47
So if you have Blender 2.71 installed, it should run without any issue.
If you have Blender 2.72, you first need to change `STRICT_MAX_BLENDER_VERSION` in the file above (`bin/morse.in`) to something like `2.73` and re-install MORSE. This should be soon release as MORSE 1.2.2 (cf bug #582)

**Comment by adegroote** [comment]
After a git pull in the homebrew recipe, you should be able to get 1.2.2

**Comment by seantrott** [comment]
Thanks for your help. I have Blender 2.71, but I'm still getting that issue. I changed the "morse-simulator.rb" file in the "homebrew-morse" directory, as mentioned above, so that line 4 reads:
url 'https://github.com/morse-simulator/morse.git', :tag => '1.2.1'

Is there a different way I'm meant to specify that I want to use Morse version 1.2.1?

**Comment by fdevillalobos** [comment]
Hey @seantrott ... how did you solve this?
I'm having the same problem... Morse 1.3 now... and Blender 2.73... and I still cannot run because I get that message.

* Blender is compiled for Python 3.4.2 but MORSE has been compiled for Python 3.3.0! Check your MORSE build configuration or the selected Blender version.

So... did you solve it?? How?? Are you running morse on Yosemite?? Please some help. Really appreciate it.
Thanks!
Francisco.

**Comment by seantrott** [comment]
Hello,
It appears your Blender version requires a different Python version than the version of Python that Morse was linked to - I've had some similar troubles. I believe I'm using Blender 2.71 and Python 3.4.0; Blender 2.71 wants Python 3.4.0, as far as I know. So the first step is making sure your main Python3 version is compatible with your version of Blender. Which Python3 are you using on your machine?

I also fixed the Yosemite issue, which was a separate problem. I did a short write-up here for the module I'm using Morse for, which is meant to walk people through that issue: https://github.com/icsi-berkeley/ecg-specializer/blob/master/morse_installation.md

You can ignore the first part and go straight to the "Yosemite Installation" section. This might answer your questions!
-Sean
